---
root: true

plugins:
  - jest

env:
  node: true
  jest: true
  browser: true


extends:
  - "airbnb-base"
  - "plugin:jest/recommended"

rules:
  no-console: 0
  import/extensions: 0
  function-paren-newline: ["error", "multiline-arguments"]
  function-call-argument-newline: ["error", "never"]